"""staff tables

Revision ID: 00f94cba3487
Revises: b4cc1e355e27
Create Date: 2018-04-03 16:11:24.747878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f94cba3487'
down_revision = 'b4cc1e355e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(length=64), nullable=True),
    sa.Column('attribute_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('attribute_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('second_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('employment_date', sa.Date(), nullable=True),
    sa.Column('dismissal_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('attribute_values',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_string', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.attribute_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'category_id', 'attribute_id')
    )
    op.create_table('category_attribute_link',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.attribute_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id')
    )
    op.create_table('staff_category_link',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'category_id')
    )
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_table('staff_category_link')
    op.drop_table('category_attribute_link')
    op.drop_table('attribute_values')
    op.drop_table('staff')
    op.drop_table('categories')
    op.drop_table('attributes')
    # ### end Alembic commands ###
